shotgun_api3/lib/sgtimezone.py

so that dates are pickle-able and convertable using strftime.

For #35260: Refactoring scoping of sgtimezone 

---

shotgun_api3/shotgun.py

- Only supports uploads of files attached to Versions for now.

For #38721: Added support for direct upload to S3

---

shotgun_api3/shotgun.py

For #38721: Fixed upload regression for sites prior to V 7.0.10

---

shotgun_api3/shotgun.py

- Added multi-part uploads to support uploads of files > 5 GB

For #40884: Extend support for direct uploads to S3

---

shotgun_api3/shotgun.py

Argh. Wrong pull request merged. Reverting until validated.
Reverts shotgunsoftware/python-api#137

Revert "For #40884: Extend support for direct uploads to S3"

---

shotgun_api3/shotgun.py

Requires code not merged into Shotgun master just yet...

First pass at supporting optimized pagination.

---

shotgun_api3/lib/mockgun/mockgun.py

We needed to mock percent fields in some tests.
I would like to do some unittests on implementations as such. Do you have any advises?

Mockgun percent

---

shotgun_api3/__init__.py
shotgun_api3/shotgun.py

Created a new exception to detect an attempt at authenticating with a login/password pair when SSO is enabled on the site.
It makes it easier for scripts to handle this situation. With that, a general Fault is raised.

Added handling of SSO by creating a new exception

---

shotgun_api3/lib/mockgun/mockgun.py

To make it easier to review, use `&w=1` at the end of the URL

Added get_session_token to mockgun

---

shotgun_api3/shotgun.py

Updated the returned tokens, as per our discussions.

Updated the info() return values

---

HISTORY.rst
README.md
shotgun_api3/__init__.py
shotgun_api3/shotgun.py
tests/test_api.py

* When called for a source entity for which the thumbnail is not ready

For SG-13320: shared_thumbnail  raise a specific error

---

docs/cookbook/attachments.rst
docs/cookbook/examples/basic_upload_thumbnail_version.rst
docs/reference.rst
shotgun_api3/shotgun.py

SG-12960 doc edits and additions for direct upload to s3

---

tests/test_api_long.py

Disables a test that fails on the CI servers.

Disable failing test

---

HISTORY.rst
appveyor.yml
tests/test_api.py

CI server was updated so we're fixing the build.

Testing CI

---

docs/authentication.rst
docs/cookbook.rst
docs/cookbook/examples/ami_handler.rst
docs/cookbook/examples/ami_version_packager.rst
docs/cookbook/smart_cut_fields.rst
docs/cookbook/tasks/task_dependencies.rst
docs/reference.rst
setup.py

This PR replaces ZD urls to AKN and developer urls

SG-21170-ROUND2 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

---

README.md
docs/advanced.rst

This PR replaces ZD urls to AKN and developer urls

SG-21170-ROUND3 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

---

docs/cookbook/examples/ami_handler.rst

Updating AMI documentation code example to run with Python 2/3.

SG-24976 Update AMI Documentation To_Support Python 3

---

shotgun_api3/shotgun.py
tests/base.py
tests/test_client.py

This pr add retries for 503 on S3 uploads.

SG-20154 Add Retries on 503 Errors when uploading to S3 in Shotgun python-api

---

azure-pipelines.yml

- Replace MacOS 10.11 with 12
- Replace WIndows 2019 with 2022

SG-29004 Upgrade deprecated azure pipelines machines

---

tests/base.py
tests/test_api.py

Create dedicated entities on ShotGrid for each test instead of re-using pre-created ones.

SG-31925 Fixup follow flaky tests

---

azure-pipelines-templates/run-tests.yml
tests/example_config

Revert some changes from #320 to allow unit tests run again

Use Azure Pipelines group variables

---

docs/reference.rst

Align wording with tk-core
Related to shotgunsoftware/tk-core#1004

SG-38301 Review the documentation regarding the `SHOTGUN_API_CACERTS` variable

---

shotgun_api3/lib/mockgun/mockgun.py
tests/test_api.py
tests/test_mockgun.py

Packaging some community contributions. We checked that CI runs smoothly. They include new unit tests and just one has been updated to something that makes sense.
- **REJECTED**: CI didn't pass.

SG-37203 Apply mockgun improvements

---

HISTORY.rst

With this release, we can test and close SG-27368.

Packaging for v3.8.3

---

docs/advanced.rst

This pull request updates the support contact information to the current Autodesk support page.
The same change was done in the following repositories:
| Repo | PR |
|------|----|
| python-api | shotgunsoftware/python-api#411 |
| tk-3dsmax | shotgunsoftware/tk-3dsmax#54 |
| tk-aftereffects | shotgunsoftware/tk-aftereffects#61 |
| tk-alias | shotgunsoftware/tk-alias#221 |
| tk-config-default2 | shotgunsoftware/tk-config-default2#187 |
| tk-config-rv | shotgunsoftware/tk-config-rv#11 |
| tk-core | shotgunsoftware/tk-core#1054 |
| tk-desktop | shotgunsoftware/tk-desktop#204 |
| tk-desktop2 | shotgunsoftware/tk-desktop2#47 |
| tk-flame | shotgunsoftware/tk-flame#156 |
| tk-flame-export | shotgunsoftware/tk-flame-export#61 |
| tk-flame-review | shotgunsoftware/tk-flame-review#40 |
| …

SG-40165 Update support URL
