- README.md
- shotgun_api3/shotgun.py
- tests/test_client.py
**Commit Details:**
* As of Shotgun 5.4.10, session tokens are distinguished by a "product" field depending on how they were created.  If the appropriate product is not supplied with the session_token, any authentication request with that token will fail.
* We add an optional "extra_auth_params" member to the Config object so  that we can pass in the "product" when needed, and other supplementary params  we might add in the future.
* New client_test "test_extra_auth_params()" succeeds with changes in this commit.
* README.md refreshed a little.
**Usage Example**
```python
def create_sg_connection(self):
"""
Create a Shotgun instance using the script user's credentials.
:returns: A Shotgun instance.
"""
shotgun_obj = Shotgun(
self.get_host(),
session_token=self._session_token, …
```
> #35872 shotgun.py: optional extra_auth_params added to Config object

- shotgun_api3/shotgun.py
We want to ensure that we're explicitly closing our file handler in download_attachment, so that we don't throw an error in cases where Python's garbage collector doesn't close the file.
> For #36143: Explicitly closing download_attachment file handler

- shotgun_api3/shotgun.py
- tests/base.py
- tests/example_config
- tests/test_api.py
This update will allow for updating multi-entity fields without having to pull down the field's entire dataset first.
It uses the new parameter ```multi_entity_update_modes``` on the update method to specify one of 'add', 'remove', or 'set'.
As this update is tied to a change on the server-side, it should not be merged until that pull request is merged and released.
> For #10692: Option to use add/remove/set modes when updating multi-entity fields

- tests/base.py
SgTestConfig is missing a reference to the playlist_code config.
> For #36311: Adding playlist_code to SgTestConfig

- HISTORY.rst
- shotgun_api3/shotgun.py
- tests/test_api.py
It was possible to attempt to upload a zero-byte file which can cause all sorts of issues but most notably it generates a ServerError which is misleading to the user. We now check the file exists and is not empty before calling `upload()`. If the file is empty, and exception is now raised stating the issue.
> for #39129: catch empty files before uploading() and raise exception.

- docs/cookbook/tasks/updating_tasks.rst
- docs/reference.rst
* Fixes the formatting in the `API Cookbook > Working With Tasks` section. The left nav TOC was wrapping all over the place and wonked out. This simplifies the TOC.
* Adds an index to the top of the API Reference section for `Shotgun()` to show a list of methods grouped by type.
*Note these docs are already published at http://developer.shotgunsoftware.com/python-api*.
> Update v3.0.32 docs formatting

- shotgun_api3/lib/mockgun.py
We faced the following warnings from mockgun when we tried to use the status_list on shots:
* `ShotgunError: The not_in operator is not supported on the status_list type` (fixed in `_compare`)
* `ShotgunError: Field Shot.sg_status_list: Handling for Shotgun type status_list is not implemented` (fixed in `_validate_entity_data`)
Let me know if it should be done another way.
Best,
Jordi
> mockgun: add support of status_list

- shotgun_api3/shotgun.py
- tests/test_api.py
Changes:
- Adding method `Shotgun.following`, which returns a list of entity instances a HumanUser is following. It can optionally be passed a project description and/or an entity type name. eg.:
- `sg.following( {"type":"HumanUser", "id":1234}, project={"type":"Project", "id":1234}, 
entity_type="Task" )`
- Adding method `ServerCapabilities.ensure_user_following_support`, which ensures we're not calling this function if the server-side doesn't support it.
- As `Follow` isn't treated like a regular entity:
- `TestFollow.setUp` was updated to clear the server state of pre-existing follows before each test. 
- `TestFollow.test_follow` & `TestFollow.test_unfollow` were combined into one method `TestFollow.test_follow_unfollow` to match this test flow.
- Added method …
> For #40631: Adding following method and updating unit tests

- shotgun_api3/shotgun.py
:man_facepalming:
I thought that the revert was pending with the revert pull request being opened (#139) and the *actual* revert effect on master was still pending, but it had been done immediately and that pull request #139 was opened to bring it back. Looking at the diff would have been helpful. Meh.
This pull request **brings back** pull request #137, which was:
- committed by mistake to master by myself this morning as commit
ca53f5f6988d71ac69c418e08c83ed3a026fe06c
- recommitted by mistake by myself again #139 as commit 5e3142991628e3174207d53906ecf5470fc3ecd4
(yes, I'll get some sleep tonight)
> For #40884: Extend support for direct uploads to S3

- tests/base.py
Ensured a tuple is used for LiveTestBase.sg_version so comparisons against tuples like (7,0,0) work.
> For #41470, fix skipped tests

- shotgun_api3/lib/mockgun/mockgun.py
- tests/test_mockgun.py
Hi, 
We started using mockgun for testing our pipeline at Squeeze.
However I've realized that some calls to find that worked with Shotgun failed with mockgun.
This was mainly related to :
- Using nested multi-entity when filtering (ex: ["project.Project.users.HumanUser.login", "is", "user1"])
- Requested fields (indirectly through the order argument) not being returned.
I've made the changes and implemented some additional tests, hope it help!
> fix nested multi-entities query

- shotgun_api3/lib/mockgun/mockgun.py
- tests/test_mockgun.py
While writing unit tests in Toolkit I stumbled upon this bug, where searching for a sub-entity field would crash if any of the sub-entity field was set to `None`. See unit test for more info.
Also, PEP8ed `mockgun.py`. The actual fix [is on line 679](https://github.com/shotgunsoftware/python-api/pull/172/files#diff-443157c398f7038db0d1eb0401aa7d4eR679)
> For #46904, site wide tk-config-default2

- tests/test_client.py
When using URL based authentication, the authorization header is being unquoted. If your test user has `%` in it's password, the test would fail.
> Ensures the password is properly unquoted for the test

- shotgun_api3/shotgun.py
- tests/test_api.py
Makes use of the new `s3_enabled_upload_types` info object to see if an upload supports and should be sent to cloud storage.
> SG-6892 - Use s3_enabled_upload_types for cloud uploads

- shotgun_api3/shotgun.py
Reading/writing a large file all at once can cause a MemoryError or an OverflowError. Using `shutil.copyfileobj` seems to solve the issue.
> Avoid errors when uploading large files

- shotgun_api3/lib/mockgun/mockgun.py
This is to match the filters with the regular api version, for cases like this:
sg.find_one('Version', [ **['code', 'not_in', ['Hello Mockgun World !']** ]], ['description'])
> Added mockgun support for "not_in" operator when using text fields

- docs/reference.rst
Aleksandar Kocic (koaleksa) pointed out that we don't have documentation for the following method in our Python API docs:
https://community.shotgunsoftware.com/t/undocumented-shotgun-api-method-shotgun-following-entity/644
This change adds that documentation.
> Adding the following method to the documentation

- appveyor.yml
- shotgun_api3/lib/mimetypes.py
- tests/base.py
- tests/test_api.py
As part of the python3 compatibility pass, the bundled mimetypes module was made python3 compatible.  This was not necessary as this module is only used in certain versions of python2.  Revert the compatibility changes and add a comment explaining why the module is not python3 compatible.
> SG-13608 Revert mimetypes module

- shotgun_api3/shotgun.py
- tests/test_api.py
Adds support for updating field visibility through the API.
This can be achieved by the following code:
```python
sg.schema_field_update("Asset", "sg_my_custom_field", {"visible": False}, project)
```
where `project` is a dictionary referring to project in which we want to hide "sg_my_custom_field". Restoring visibility can be done via
```python
sg.schema_field_update("Asset", "sg_my_custom_field", {"visible": True}, project)
```
Note: The build is currently failing because the feature hasn't been released in Shotgun. Once the feature is released the test will be updated to the right version check and the feature commited.
> SG-10151: set field visibility via API

- shotgun_api3/shotgun.py
Added some comments explaining the relationship between the certificate authority certificates, the API and how these interact with `httplib2` and `urllib2`
Let me know if there's anything else you feel I should put in there.
> Gives an explanation of how ssl works with our API

- shotgun_api3/lib/mockgun/mockgun.py
- shotgun_api3/shotgun.py
- tests/test_mockgun.py
Mockgun never initialized the values inside the `_Config` instance, which is causing some issues in Python 3 because of `None` values being passed into `urllib` methods.
I've added the required tests.
> SG-13267: Config fixes for Mockgun

- shotgun_api3/lib/six.py
We need the latest version of six to get rid of the collection.abc warning related to moved classes in Python 3.3+
> SG-14555, update six to the latest version

- shotgun_api3/lib/httplib2/__init__.py
- shotgun_api3/lib/sgsix.py
- tests/test_api.py
Update sgsix module to include additional functionality added during port of tk-core.
Update the httplib2 import procedure to ensure that members not exposed in `__all__` are still available as expected.
> SG-13264 Update sgsix, fix httplib2 import

- shotgun_api3/lib/httplib2/README.md
- shotgun_api3/lib/httplib2/python2/__init__.py
In certain situations IronPython2.7 doesn't search the local directory on absolute imports. Fixing the module locally until the next httplib2 release which should include the fix.
> SG-16899 httplib2 relative import

- .travis.yml
- HISTORY.rst
- README.md
- appveyor.yml
- docs/cookbook/examples/ami_version_packager.rst
- docs/installation.rst
- shotgun_api3/lib/README.md
- shotgun_api3/lib/mockgun/mockgun.py
- shotgun_api3/shotgun.py
- tests/base.py
Rebranded, and fixed a few warnings to make the output of the doc generation process a little cleaner.
> SG-22787: Shotgun to ShotGrid

- shotgun_api3/shotgun.py
- tests/test_client.py
Will retry 3 times with ascending backoff times for simple (ie: non-upload/download) API calls.
> Initial implementation of retries on 502 response.

- tests/test_api.py
BIg thank to @bolducl who found the problem with the tests.
> SG-24020: Fixes a bug in the schedule test

- README.md
- docs/installation.rst
Remove python 2.7 from readme and docs sections "Minimum requirements"
> SG-29417 [Python API Documentation] Update Python version requirements

- docs/cookbook/usage_tips.rst
- shotgun_api3/shotgun.py
- Clarify some parts of Entity Fields section.
- Clarify some parts of Combining Related Queries section.
- Update doc navigability with links.
> SG-21729 Update docs for entity fields.

- shotgun_api3/shotgun.py
Preview of the changes ( the same changes have been applied to the two functions )
> SG-30223 Reformat code examples to prevent text overflow

- README.md
- azure-pipelines-templates/run-tests.yml
- shotgun_api3/shotgun.py
We need to ~~rebase #305 and~~ complete SG-32847 before testing this again.
- Upgrades httplib2 module
- Upgraded syntax
- pyparsing should be upgraded. We can work on this later since this needs more testing.
> SG-32806 Enable support for Python 3.10 in CI

- tests/test_api.py
Removing a flaky assertion that compares two calls to work_schedule_read() with the same parameters, as it serves no clear purpose and occasionally fails in the CI. Running this same test by making real calls to the python-api correctly returns the `WorkDayRules` defined between the given `start_date `and `end_date`.
> SG-31927 Flaky Test In python-api Test Work schedule

- docs/index.rst
We don't even use Travis anyway
> Travis badge image is no working anymore

- tests/test_api.py
This PR fixes flaky tests that contain the following errors:
```
- AssertionError: 'image/png' != 'image/jpeg'
- AssertionError: '304' != '200'
```
Allows upload requests with status '304' in the thumbnail upload tests, because sometimes when the response hasn't been modified, this status informs the client that the response has not changed, so the client can continue using the same cached version.
Also supports transient placeholder PNG file content types in the response payload, since sometimes it takes longer for the previously uploaded image requested to be available from media storage, and we have previously tested that the image was successfully uploaded.
> Fix flaky upload tests.

- shotgun_api3/shotgun.py
The ShotGrid API3 recently introduced two new endpoints:
- user_subscriptions_create
- user_subscriptions_read
> SG-33870 Add methods for the user_subscriptions API end points

- azure-pipelines-templates/run-tests.yml
- shotgun_api3/shotgun.py
- tests/example_config
> SG-34199 Comment typing annotation breaks Python 2 compatibility

- shotgun_api3/shotgun.py
- tests/base.py
- tests/test_client.py
- Follow up work from #263
- Include error 500s retries when uploading to S3 cloud
> SG-34197 Retry S3 uploads on error 500

- tests/ci_requirements.txt
New version of [pytest-nunit](https://github.com/pytest-dev/pytest-nunit/releases) was released yesterday. No need for this line anymore.
> Remove pytest-nunit fix for CI

- docs/cookbook/usage_tips.rst
- docs/index.rst
Documentation title changed from Flow Production Tracking Python API3 to Flow Production Tracking Python API
> SG-34983 Documentation title changed from API3 to API

- shotgun_api3/shotgun.py
- tests/base.py
- tests/test_client.py
- Add retry only when encountering an URLError
- Adopt the existing strategy
- Add tests
> SG-35165 Retry on URLError

- shotgun_api3/shotgun.py
- tests/test_api.py
Use the existing re-attempt strategy in case of SSLEOFError
> SG-34910 Fixup SSLEOFError exception

- .gitignore
- azure-pipelines-templates/run-tests.yml
- tests/base.py
- tests/example_config
- tests/test_api.py
Ticket entity is disabled by default on ShotGrid (it seems so).
I'm making unit tests dependant-free on this entity. It seems they were enabled when these tests were implemented, but now this is making it harder to test locally with fresh SG sites.
> SG-35018 Remove Ticket entity reference and prepare this to run in CI

- .coveragerc
- azure-pipelines-templates/run-tests.yml
- shotgun_api3/shotgun.py
- tests/base.py
- tests/test_api.py
- tests/test_api_long.py
Now all tests use the same authentication credentials. By default, it uses and expects a script name/key pair provided on the config file. However, a special flag `SG_JENKINS` is considered to use username/password only for SG sites that haven't created a script.
Before | After
-- | --
Argument `durations` was added to pytest to detect the slowest tests and improve them in the future
Step 1: remove `script_name`/`api_key` from config file
Step 2: add `human_login` / `human_password` to config file
Step 3: run
```bash
export SG_JENKINS=1
pytest tests/test_api.py
```
> SG-35018 Condition auth for Jenkins environment

- shotgun_api3/lib/mockgun/mockgun.py
- shotgun_api3/lib/sgutils.py
- shotgun_api3/shotgun.py
- tests/base.py
- tests/test_client.py
- ensure_* functions replaced by function from sgutils.py.
- six types replaced by native
> SG-29997 - FIRST PHASE Python2 removing

- docs/cookbook/usage_tips.rst
- Corrected the import statement for the Shotgun class to use the proper module path 'shotgun_api3.Shotgun'
> Fix incorrect Shotgun import in Python API example

- shotgun_api3/shotgun.py
- tests/test_unit.py
This is a follow up work from #360 in this case including support for `in` and `not_in` [operators](https://developers.shotgridsoftware.com/python-api/reference.html#operators-and-arguments) for lists of entities.
- find
- summarize
- text_search (API query_display_name_cache)
The change should transform calls like:
```python
sg.find("Asset",
[[
"project", "in",
[
{
"created_at": datetime.datetime(2015, 12, 16, 11, 2, 10, tzinfo),
"id": 72,
"name": "Demo: Game",
"type": "Project",
},
{
"created_at": datetime.datetime(2015, 12, 16, 11, 2, 10, tzinfo),
"id": 73,
"name": "Demo: Game 2",
"type": "Project",
}
]
]]
)
```
as if the following had been called:
```python
sg.find('Asset', [['project', 'in', [{'id': 72, 'type': 'Project'}, {'id': 73, 'type': 'Project'}]]]) 
```
> SG-37544 Include the "in" and "not_in" operators for payload optimization

- software_credits
> SG-37280 Update Software Credits

- shotgun_api3/shotgun.py
There's a flaky disconnection when the publisher uploads the thumbnail. The most common errors are:
- Connection closed by peer
- URLopen error EOF occurred in violation of protocol ssl.c:1006
They seem to be related to TLS handshakes. While testing on local machines we consistently reproduced this with the following change: Move the connection opener to the retry block and change `CACertsHTTPSHandler` parent class.
> SG-35712 Prevent flaky disconnection when uploading thumbnails on publish

- azure-pipelines-templates/run-tests.yml
- tests/test_api.py
1️⃣  We're starting to get these errors on Azure Pipelines:
```
Starting: UsePythonVersion
==============================================================================
Task         : Use Python version
Description  : Use the specified version of Python from the tool cache, optionally adding it to the PATH
Version      : 0.248.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-python-version
==============================================================================
##[warning]You should provide GitHub token if you want to download a python release. Otherwise you may hit the GitHub anonymous download limit.
##[error]Failed to download Python from the Github Actions python registry …
```
> Remove Python 3.7 from CI

- tests/test_api.py
On #377 we assumed we could fix a broken unit test, but this is the definite fix.
> Fix `creative_review_settings` test

- docs/cookbook/attachments.rst
- docs/reference.rst
This pull request updates the documentation for handling local file fields and local storage references.
- Add missing information regarding data structure regarding the `relative_path` and `local_storage` fields
- Provide an additional example for submitting a path referencing a `LocalStorage` by name
- Minor readability improvements
> SG-4373 Improve documentation about local file references

- shotgun_api3/shotgun.py
- tests/test_api.py
- tests/test_client.py
- tests/test_unit.py
Not much here but will make the next PRs easier to read.
* #398
* #399 
* #400 
* #401
* #402
* #403
* #404
* #405
* #395
* #372
> SG-38306 Python2 Removal - Part 1 - Import order
